# -*- coding: utf-8 -*-
"""Pınar_Kınay.ipynb adlı dosyanın kopyası adlı dosyanın kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dnv9POhnvd_jpWP1tMLdapUXkfjCHAG0

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on Drive.
ex: atay_ilgun_MIDTERM.ipynb

Describe what ML is in 50 words.
"""

Machine learning is a construction of algorithms. In addition, An algorithm isn’t a particular calculation, but the method followed when making the calculation.For example, if you want to calculate the average between two numbers, you can use a simple algorithm. There are some kind of program instructions by making data predictions or decisions. 
ML is a include of generic algorithm and own logic based on the data. Machine Learning is a method used to complex algorithms. Also, there are lots of usage area. For example; supervised learning, semisupervised learning, unsupervised learning and reinforcement learning.

"""Give 3 examples of ML in practical use in todays world - also, meditate on how it is being utilised as well."""

1)Siri / Alexa vs.:What you want by giving voice commands over the phone
2)Google E*mail spam:Provides interpersonal communication and correspondence via e-mail
3)Google Translate: Change a different kind of universal language.)

"""In ML terminology what is an 'example', 'feature', 'label' and 'feature vector'?"""

ML feature: A feature is an individual measurable property or characteristic of a phenomenon being observed. Features are usually numeric, but structural features such as strings and graphs are used in syntactic pattern recognition
ML label: Briefly, feature is input; label is output. A feature is one column of the data in your input set. The label is the final choice, such as dog, fish, iguana, rock, etc.
ML feature vector: In machine learning, feature vectors are used to represent numeric or symbolic characteristics, called features, of an object in a mathematical, easily analyzable way

"""In 100 words meditate on how future advancements on AI could affect your work practice as a communication designer."""

For a User experience, I want to talk about my own thoughts on artificial intelligence. One of the innovations to shape the future is the formation and rise of artificial intelligence. We know that the most
powerful thing we have ever experienced is our brains and intelligence, but in the future, thanks to artificial intelligence, many things can be done in a persons sense of fear. For example, our mobile phones have managed to take over US. It can access our memories
and find new information in a very fast time. The definition of this is artificial intelligence that will deal with the domination of the world. Nowadays, In the race for artificial intelligence development, billions of dollars are spent, and as a result everything is wanted for every object to be intelligent.

"""Try to describe how you learn in algorithmic terms."""

As an effective method, an algorithm can be expressed within a finite amount of space and time. I give an example, designing an algorithm and documentation preparation.

"""Create a python dictionary for your name surname and year of birth."""

pk = {"name" : "pınar" , "surname" : "kınay", "birthyear" : "1995"}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if pk["name"][0] == "a":
  print("my initial is a")

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len(pk['surname']) & 3 == 0:
  print('it is divisible')
else:
  print("it is not divisible")

"""Change your year of birth to 2678."""

pk["birthyear"] = 2678
print(pk)

"""Create a loop that goes through 20 to 40 and prints out the numbers that are divisble by 5."""

list_1 = range(20,40)
for everynumber in list_1:
  if everynumber % 5==0:
    print(everynumber)

"""Check the PDF on the Drive and calculate the neurons. Put all neurons and weights in python and do the calculation with them."""

print(0.87*0.06+0.12*0.12+0.62*0.47)

"""Using the code here:
https://github.com/anishathalye/neural-style
create a ***style transfer*** image.

Upload it along with this file.

You might need a file while doing this, it also is on the Drive!
"""